resources:
  - deployments.yaml
  - services.yaml

namespace: crosschain-api

secretGenerator:
  - name: crosschain-api-config
    files:
      - config.prod.yaml
      - config-override.prod.yaml

images:
  - name: 133735975201.dkr.ecr.us-east-1.amazonaws.com/prod/fanstech/crosschain-core
    newTag: main-20250822-0741-a438beb@sha256:151ed98c6501ffe4411b9fcee9bbbb8e840c087aef35aa08f8743baef73b440d
