apiVersion: v1
kind: Service
metadata:
  name: crosschain-api
spec:
  ports:
    - port: 3010
      protocol: TCP
      targetPort: http
  selector:
    environment: prod
    app.kubernetes.io/name: crosschain-api
    app.kubernetes.io/instance: crosschain-api