

# "start-bot"
# "start-task-base"
# "start-task-bsc"
# "start-task-solana"
# "start-task-ethereum"
# "start-task-tron"

services:
  redis:
    image: valkey/valkey:8-apline
    restart: always

  tomo-crosschain-node:
    image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/dev/fanstech/crosschain-core:dev-v2-20250711-0608-be90684@sha256:5ae3841cb7e08a9ad02fdb0d6e06b61f64d7c6825a57f4232ac75fb9ced335f2
    restart: always
    depends_on:
      - redis
  