

# "start-bot"
# "start-task-base"
# "start-task-bsc"
# "start-task-solana"
# "start-task-ethereum"
# "start-task-tron"

# node template
x-node: &node
  image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/dev/fanstech/crosschain-core:dev-v2-20250711-0608-be90684@sha256:5ae3841cb7e08a9ad02fdb0d6e06b61f64d7c6825a57f4232ac75fb9ced335f2
  restart: always
  depends_on:
    - redis
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml

services:
  redis:
    image: valkey/valkey:8-apline
    restart: always
    command:
      - valkey-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  bot:
    <<: *node
    container_name: crosschain-bot
    environment:
      START_OPTS: "start-bot"

  task-base:
    <<: *node
    container_name: crosschain-task-base
    environment:
      START_OPTS: "start-task-base"

  task-bsc:
    <<: *node
    container_name: crosschain-task-bsc
    environment:
      START_OPTS: "start-task-bsc"

  task-solana:
    <<: *node
    container_name: crosschain-task-solana
    environment:
      START_OPTS: "start-task-solana"

  task-ethereum:
    <<: *node
    container_name: crosschain-task-ethereum
    environment:
      START_OPTS: "start-task-ethereum"

  task-tron:
    <<: *node
    container_name: crosschain-task-tron
    environment:
      START_OPTS: "start-task-tron"