

# "start-signer-task-base"
# "start-signer-task-bsc"
# "start-signer-task-solana"
# "start-signer-task-ethereum"
# "start-signer-task-tron"

# node template
x-node: &node
  image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/prod/fanstech/crosschain-core:main-20250723-0643-ecb2a59@sha256:963a56014b5c3cb8943617b6d23ad99d8837bac833c631b016bbc480f7d17295
  restart: always
  depends_on:
    - redis
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml
    - ./config-override.prod.yaml:/app/config-override.prod.yaml

services:
  redis:
    image: valkey/valkey:8-alpine3.22
    restart: always
    command:
      - valkey-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  task-base:
    <<: *node
    container_name: crosschain-task-base
    environment:
      START_OPTS: "start-signer-task-base"
      NODE_ENV: "prod"

  task-bsc:
    <<: *node
    container_name: crosschain-task-bsc
    environment:
      START_OPTS: "start-signer-task-bsc"
      NODE_ENV: "prod"

  task-solana:
    <<: *node
    container_name: crosschain-task-solana
    environment:
      START_OPTS: "start-signer-task-solana"
      NODE_ENV: "prod"

  task-ethereum:
    <<: *node
    container_name: crosschain-task-ethereum
    environment:
      START_OPTS: "start-signer-task-ethereum"
      NODE_ENV: "prod"

  task-tron:
    <<: *node
    container_name: crosschain-task-tron
    environment:
      START_OPTS: "start-signer-task-tron"
      NODE_ENV: "prod"