

# "start-signer"

# node template
x-node: &node
  image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/dev/fanstech/crosschain-core:dev-v2-20250713-1016-df16405@sha256:e635840e15cc6105017467bef45f940de06a89a63dd19558faf6ff74b217a77a
  restart: always
  depends_on:
    - redis
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml
    - ./config-override.prod.yaml:/app/config-override.prod.yaml

services:
  redis:
    image: valkey/valkey:8-alpine3.22
    restart: always
    command:
      - valkey-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  crosschain-signer:
    <<: *node
    container_name: crosschain-signer
    ports:
      - 3333:3333
    tty: true
    stdin_open: true
    environment:
      START_OPTS: "start-signer"
      NODE_ENV: "prod"
