

# "start-signer"

# node template
x-node: &node
  image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/dev/fanstech/crosschain-core:dev-v2-20250711-0919-c838c8f@sha256:a8a100edcb033449148ba5ce99614ab09189c94924a3bf67f19cd330bdd02cf8
  restart: always
  depends_on:
    - redis
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml
    - ./config-override.prod.yaml:/app/config-override.prod.yaml

services:
  redis:
    image: valkey/valkey:8-alpine3.22
    restart: always
    command:
      - valkey-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  crosschain-signer:
    <<: *node
    container_name: crosschain-signer
    ports:
      - 3333:3333
    environment:
      START_OPTS: "start-signer"
      NODE_ENV: "prod"
