

# "start-signer"

# node template
x-node: &node
  image: 133735975201.dkr.ecr.us-east-1.amazonaws.com/prod/fanstech/crosschain-core:main-20250816-0347-502fb80@sha256:e69c557ae6ec907fe4238cdd215fd9cecebb65ced9c10d890cccc13c70043d29
  restart: always
  depends_on:
    - redis
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml
    - ./config-override.prod.yaml:/app/config-override.prod.yaml

services:
  redis:
    image: valkey/valkey:8-alpine3.22
    restart: always
    command:
      - valkey-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  crosschain-signer:
    <<: *node
    container_name: crosschain-signer
    ports:
      - 3333:3333
    tty: true
    stdin_open: true
    environment:
      START_OPTS: "start-signer"
      NODE_ENV: "prod"
